name: zzsn
dependencies:
  - python=3.9
  - conda-forge::jupyterlab
  - conda-forge::jupyterlab-lsp
  - conda-forge::python-language-server
  - conda-forge::nodejs
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - pytorch::pytorch=1.8.1
  - pytorch::torchvision=0.9.1
  - pytorch::torchaudio=0.8.1
  - cudatoolkit=11.1
  - pip:
      - -r file:requirements.txt
